Repository not-elm/bevy_vrm1, pull requests merged in 2025-06, with the labels that each got.

#18 fix: outlineWidthFactor
  src/vrm/gltf/materials.rs
  src/vrm/mtoon/outline.rs
Labels: bug

#20 fix: vrma rotation retarget
  CHANGELOG.md
  assets/vrma/VRMA_02.vrma
  assets/vrma/VRMA_03.vrma
  assets/vrma/VRMA_04.vrma
  assets/vrma/VRMA_05.vrma
  assets/vrma/VRMA_06.vrma
  assets/vrma/VRMA_07.vrma
  src/vrm.rs
  src/vrma/retarget/bone.rs
Labels: bug

#22 Fix outline rendering pass
  CHANGELOG.md
  Cargo.toml
  src/lib.rs
  src/vrm.rs
  src/vrm/gltf.rs
  src/vrm/gltf/materials.rs
  src/vrm/mtoon.rs
  src/vrm/mtoon/material.rs
  src/vrm/mtoon/material/outline.rs
  src/vrm/mtoon/outline.rs
  src/vrm/mtoon/outline.wgsl
  src/vrm/mtoon/outline/pipeline.rs
  src/vrm/mtoon/outline/render_command.rs
  src/vrm/mtoon/outline_pass.rs
  src/vrm/mtoon/outline_pass/phase_item.rs
  src/vrm/mtoon/outline_pass/pipeline.rs
  src/vrm/mtoon/outline_pass/render_command.rs
  src/vrm/mtoon/outline_pass/view_node.rs
  src/vrm/mtoon/setup.rs
  src/vrm/mtoon_fragment.wgsl
  src/vrm/mtoon_types.wgsl
  src/vrm/mtoon_vertex.wgsl
Labels: bug

#23 update: add prelude modules
  examples/look_at_cursor.rs
  examples/look_at_target.rs
  examples/multiple_lights.rs
  examples/simple.rs
  examples/spring_bone.rs
  examples/vrma.rs
  src/lib.rs
  src/system_param.rs
  src/system_param/child_searcher.rs
  src/vrm.rs
  src/vrm/expressions.rs
  src/vrm/humanoid_bone.rs
  src/vrm/spawn.rs
  src/vrm/spring_bone.rs
  src/vrm/spring_bone/registry.rs
  src/vrma.rs
  src/vrma/animation.rs
  src/vrma/animation/play.rs
  src/vrma/animation/setup.rs
  src/vrma/gltf/extensions.rs
  src/vrma/loader.rs
  src/vrma/retarget.rs
  src/vrma/retarget/bone.rs
  src/vrma/retarget/expressions.rs
  src/vrma/spawn.rs
Labels: improvement, breaking-change

#24 Add marker components to each bone
  Cargo.toml
  examples/look_at_target.rs
  src/macros.rs
  src/vrm.rs
  src/vrm/humanoid_bone.rs
  src/vrm/humanoid_bone/bones.rs
  src/vrm/loader.rs
  src/vrm/look_at.rs
  src/vrm/spring_bone/setup.rs
  src/vrma.rs
  src/vrma/retarget/bone.rs
Labels: breaking-change

#25 serde feature flag
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.toml
  README.md
  src/macros.rs
  src/vrm.rs
  src/vrm/gltf/extensions/vrmc_vrm.rs
  src/vrm/look_at.rs
  src/vrm/mtoon.rs
  src/vrm/mtoon/material.rs
  src/vrm/mtoon/material/outline.rs
  src/vrm/mtoon/material/rim_lighting.rs
  src/vrm/mtoon/material/shade.rs
  src/vrm/mtoon/material/uv_animation.rs
  src/vrm/spring_bone.rs
  src/vrm/spring_bone/registry.rs
  src/vrma.rs
  src/vrma/animation.rs
  src/vrma/animation/setup.rs
  src/vrma/retarget/expressions.rs
Labels: breaking-change

#26 add system-set
  CHANGELOG.md
  Cargo.toml
  src/lib.rs
  src/system_set.rs
  src/vrm/look_at.rs
  src/vrm/spring_bone/update.rs
  src/vrma/retarget.rs
  src/vrma/retarget/bone.rs
  src/vrma/retarget/expressions.rs
Labels: improvement

#27 fix: vrm and vrma components export
  CHANGELOG.md
  src/vrm.rs
  src/vrm/look_at.rs
  src/vrma.rs
  src/vrma/animation.rs
Labels: improvement

#28 Fix springbone
  CHANGELOG.md
  src/vrm/gltf/extensions/vrmc_spring_bone.rs
  src/vrm/mtoon_fragment.wgsl
  src/vrm/spring_bone.rs
  src/vrm/spring_bone/registry.rs
  src/vrm/spring_bone/setup.rs
  src/vrm/spring_bone/update.rs
Labels: bug

#29 Remove skip flag
  src/vrm/mtoon_fragment.wgsl
Labels: bug

#30 Fix collider unit error
  src/vrm/gltf/extensions/vrmc_spring_bone.rs
Labels: bug

#31 Support Animation transition
  CHANGELOG.md
  Cargo.toml
  README.md
  assets/vrma/VRMA_01.vrma
  assets/vrma/VRMA_02.vrma
  assets/vrma/VRMA_03.vrma
  assets/vrma/different_pose.vrma
  examples/vrma.rs
  examples/vrma_transition.rs
  src/error.rs
  src/lib.rs
  src/system_param.rs
  src/system_param/child_searcher.rs
  src/system_param/vrm_animation_players.rs
  src/vrm.rs
  src/vrm/expressions.rs
  src/vrm/humanoid_bone.rs
  src/vrm/initialize.rs
  src/vrm/look_at.rs
  src/vrm/mtoon.rs
  src/vrm/mtoon/outline_pass.rs
  src/vrm/mtoon/outline_pass/view_node.rs
  src/vrm/spring_bone.rs
  src/vrm/spring_bone/initialize.rs
  src/vrm/spring_bone/setup.rs
  src/vrm/spring_bone/update.rs
  src/vrma.rs
  src/vrma/animation.rs
  src/vrma/animation/animation_graph.rs
  src/vrma/animation/bone_rotation.rs
  src/vrma/animation/bone_translation.rs
  src/vrma/animation/expressions.rs
  src/vrma/animation/play.rs
  src/vrma/animation/setup.rs
  src/vrma/initialize.rs
  src/vrma/retarget.rs
  src/vrma/retarget/bone.rs
  src/vrma/retarget/expressions.rs
Labels: enhancement, breaking-change
